// Code generated by "stringer -type=CommandType -trimprefix=Command"; DO NOT EDIT.

package matcher

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommandUnknown-0]
	_ = x[CommandLimit-1]
	_ = x[CommandMarket-2]
	_ = x[CommandPostOnly-3]
	_ = x[CommandCancel-4]
}

const _CommandType_name = "UnknownLimitMarketPostOnlyCancel"

var _CommandType_index = [...]uint8{0, 7, 12, 18, 26, 32}

func (i CommandType) String() string {
	if i < 0 || i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
